# Scrape Alertmanager
  - job_name: scrape_alertmanager
    metrics_path: /probe
    params:
      module: [default]
    static_configs:
      - targets:
          - http://localhost:9093/alertmanager/api/v2/alerts
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:7979
